name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push web image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/recipe-api-web:latest
          build-args: |
            CELERY_BROKER_URL=${{ secrets.CELERY_BROKER_URL }}
            DATABASE_URL=${{ secrets.DATABASE_URL }}

      - name: Build and push celery image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/recipe-api-celery:latest
          build-args: |
            CELERY_BROKER_URL=${{ secrets.CELERY_BROKER_URL }}
            DATABASE_URL=${{ secrets.DATABASE_URL }}

      - name: Build and push celery-beat image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/recipe-api-celery-beat:latest
          build-args: |
            CELERY_BROKER_URL=${{ secrets.CELERY_BROKER_URL }}
            DATABASE_URL=${{ secrets.DATABASE_URL }}

      - name: Post success message
        run: echo "Docker images successfully built and pushed to Docker Hub"
