name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push web image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/recipe-api-web:latest
          build-args: |
            SECRET_KEY=${{ secrets.SECRET_KEY }}
            CELERY_BROKER_URL=${{ secrets.CELERY_BROKER_URL }}
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            DB_PORT=${{ secrets.DB_PORT }}
            DB_HOST=${{ secrets.DB_HOST }}
            DB_NAME=${{ secrets.DB_NAME }}
            DB_USERNAME=${{ secrets.DB_USERNAME }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_HOSTNAME=${{ secrets.DB_HOSTNAME }}
            POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            EMAIL_USER=${{ secrets.EMAIL_USER }}
            EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}
            CELERY_RESULT_BACKEND=${{ secrets.CELERY_RESULT_BACKEND }}
            CELERYRESULTBACKEND=${{secrets.CELERYRESULTBACKEND}}
            CELERYRESULTBACKEND=${{CELERYRESULTBACKEND}}

      - name: Build and push celery image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/recipe-api-celery:latest
          build-args: |
            CELERY_BROKER_URL=${{ secrets.CELERY_BROKER_URL }}
            DATABASE_URL=${{ secrets.DATABASE_URL }}

      - name: Build and push celery-beat image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/recipe-api-celery-beat:latest
          build-args: |
            CELERY_BROKER_URL=${{ secrets.CELERY_BROKER_URL }}
            DATABASE_URL=${{ secrets.DATABASE_URL }}

      - name: Post success message
        run: echo "Docker images successfully built and pushed to Docker Hub"
